version: '3'
services:
    web-serv:
        image: "akagitsune/web-service:flask-app"
        ports:
        - "5000:5000"
        deploy:
            replicas: 5
            placement:
                constraints:
                    - node.role == worker
    redisdb:
        image: "redis:alpine"
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
